[gsheet]
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1afM61BTzyJMFRH_dVrdGiJNPcej-rZ_4_tYNCjMq9us/edit?usp=sharing"

[openai]
openai_api_key ="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"

[trubrics]
TRUBRICS_EMAIL='info@looksrareaf.com'
TRUBRICS_PASSWORD='Arnold2023!'

